receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          metrics_path: '/q/metrics/prometheus'
          static_configs:
            - targets: [ 'weather-consumer:9002' ]

  kafkametrics:
    cluster_alias: kafka-prod
    brokers: [ "broker:29092" ]
    protocol_version: 3.0.0
    scrapers:
      - brokers
      - topics
      - consumers
    collection_interval: 1s

processors:
  batch:

  attributes:
    actions:
      - key: environment
        value: prod
        action: insert

  filter:
    error_mode: ignore
    metrics:
        metric:
          - 'IsMatch(name, "http.*")'

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: grafana:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - prometheus
        - kafkametrics
      processors:
        - batch
        - attributes
        - filter
      exporters:
        - otlp
    logs:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
      exporters:
        - otlp
    traces:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
      exporters:
        - otlp