receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          metrics_path: '/q/metrics/prometheus'
          static_configs:
            - targets: [ 'weather-consumer:9002' ]

  kafkametrics:
    cluster_alias: kafka-prod
    brokers: [ "broker:29092" ]
    protocol_version: 3.0.0
    scrapers:
      - brokers
      - topics
      - consumers
    collection_interval: 1s

processors:
  batch:

  filter:
    error_mode: ignore
    metrics:
        metric:
          - 'IsMatch(name, "http.*")'

  resource/all:
    attributes:
      - key: deployment.environment
        value: prod
        action: upsert
      - key: service.namespace
        value: blog-open-telemetry
        action: upsert

  resource/weather-consumer:
    attributes:
      - key: service.name
        value: weather-consumer
        action: upsert
      - key: service.instance.id
        value: weather-consumer-1
        action: upsert

  resource/kafka:
    attributes:
      - key: service.name
        value: kafka
        action: upsert
      - key: service.instance.id
        value: broker-1
        action: upsert

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: grafana:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics/weather-producer:
      receivers:
        - otlp
      processors:
        - batch
        - filter
        - resource/all
      exporters:
        - otlp

    logs/weather-producer:
      receivers:
        - otlp
      processors:
        - batch
        - resource/all
      exporters:
        - otlp


    traces/weather-producer:
      receivers:
        - otlp
      processors:
        - batch
        - resource/all
      exporters:
        - otlp

    metrics/weather-consumer:
      receivers:
        - prometheus
      processors:
        - batch
        - filter
        - resource/all
        - resource/weather-consumer
      exporters:
        - otlp

    metrics/kafka:
      receivers:
        - kafkametrics
      processors:
        - batch
        - filter
        - resource/all
        - resource/kafka
      exporters:
        - otlp