receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          metrics_path: '/q/metrics/prometheus'
          static_configs:
            - targets: [ 'weather-consumer:9002' ]

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: grafana:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - prometheus
      processors:
        - batch
      exporters:
        - otlp
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp