receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: grafana:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
        - debug
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp